application: sax-lessons
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1d"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /admin
  script: main.app
  login: admin

- url: /addstudent
  script: main.app
  login: admin

- url: /editstudent
  script: main.app
  login: admin

- url: /addnotes
  script: main.app
  login: admin

- url: /editnote
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
