application: alexbakersax
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /img
  static_dir: static/img

- url: /admin
  script: main.app
  login: admin

- url: /newstudent
  script: main.app
  login: admin

- url: /newnotes
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
